// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: library.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Library;
@class LibraryItem;
@class Library_LibraryArray;
@class Library_LibraryItems;
@class URL;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - LibraryRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface LibraryRoot : GPBRootObject
@end

#pragma mark - Library

typedef GPB_ENUM(Library_FieldNumber) {
  Library_FieldNumber_URL = 1,
  Library_FieldNumber_LibraryChildren = 2,
  Library_FieldNumber_LibraryItems = 3,
};

typedef GPB_ENUM(Library_ChildType_OneOfCase) {
  Library_ChildType_OneOfCase_GPBUnsetOneOfCase = 0,
  Library_ChildType_OneOfCase_LibraryChildren = 2,
  Library_ChildType_OneOfCase_LibraryItems = 3,
};

GPB_FINAL @interface Library : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) URL *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

@property(nonatomic, readonly) Library_ChildType_OneOfCase childTypeOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) Library_LibraryArray *libraryChildren;

@property(nonatomic, readwrite, strong, null_resettable) Library_LibraryItems *libraryItems;

@end

/**
 * Clears whatever value was set for the oneof 'childType'.
 **/
void Library_ClearChildTypeOneOfCase(Library *message);

#pragma mark - Library_LibraryArray

typedef GPB_ENUM(Library_LibraryArray_FieldNumber) {
  Library_LibraryArray_FieldNumber_LibrariesArray = 1,
};

GPB_FINAL @interface Library_LibraryArray : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Library*> *librariesArray;
/** The number of items in @c librariesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger librariesArray_Count;

@end

#pragma mark - Library_LibraryItems

typedef GPB_ENUM(Library_LibraryItems_FieldNumber) {
  Library_LibraryItems_FieldNumber_ItemsArray = 1,
};

GPB_FINAL @interface Library_LibraryItems : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LibraryItem*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - LibraryItem

typedef GPB_ENUM(LibraryItem_FieldNumber) {
  LibraryItem_FieldNumber_URL = 1,
};

GPB_FINAL @interface LibraryItem : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) URL *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
