// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proscreen.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Color;
@class EdgeBlend;
@class ProPresenterScreen_CombinedArrangement;
@class ProPresenterScreen_EdgeBlendArrangement;
@class ProPresenterScreen_SingleArrangement;
@class Screen;
@class UUID;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ProPresenterScreen_ScreenType

typedef GPB_ENUM(ProPresenterScreen_ScreenType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ProPresenterScreen_ScreenType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ProPresenterScreen_ScreenType_ScreenTypeUnknown = 0,
  ProPresenterScreen_ScreenType_ScreenTypeAudience = 1,
  ProPresenterScreen_ScreenType_ScreenTypeStage = 2,
};

GPBEnumDescriptor *ProPresenterScreen_ScreenType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ProPresenterScreen_ScreenType_IsValidValue(int32_t value);

#pragma mark - ProscreenRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ProscreenRoot : GPBRootObject
@end

#pragma mark - ProPresenterScreen

typedef GPB_ENUM(ProPresenterScreen_FieldNumber) {
  ProPresenterScreen_FieldNumber_Name = 1,
  ProPresenterScreen_FieldNumber_ScreenType = 2,
  ProPresenterScreen_FieldNumber_ArrangementSingle = 3,
  ProPresenterScreen_FieldNumber_ArrangementCombined = 4,
  ProPresenterScreen_FieldNumber_ArrangementEdgeBlend = 5,
  ProPresenterScreen_FieldNumber_BackgroundColor = 6,
  ProPresenterScreen_FieldNumber_Uuid = 7,
  ProPresenterScreen_FieldNumber_BackgroundColorEnabled = 8,
};

typedef GPB_ENUM(ProPresenterScreen_Arrangement_OneOfCase) {
  ProPresenterScreen_Arrangement_OneOfCase_GPBUnsetOneOfCase = 0,
  ProPresenterScreen_Arrangement_OneOfCase_ArrangementSingle = 3,
  ProPresenterScreen_Arrangement_OneOfCase_ArrangementCombined = 4,
  ProPresenterScreen_Arrangement_OneOfCase_ArrangementEdgeBlend = 5,
};

GPB_FINAL @interface ProPresenterScreen : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) ProPresenterScreen_ScreenType screenType;

@property(nonatomic, readwrite, strong, null_resettable) Color *backgroundColor;
/** Test to see if @c backgroundColor has been set. */
@property(nonatomic, readwrite) BOOL hasBackgroundColor;

@property(nonatomic, readwrite, strong, null_resettable) UUID *uuid;
/** Test to see if @c uuid has been set. */
@property(nonatomic, readwrite) BOOL hasUuid;

@property(nonatomic, readwrite) BOOL backgroundColorEnabled;

@property(nonatomic, readonly) ProPresenterScreen_Arrangement_OneOfCase arrangementOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) ProPresenterScreen_SingleArrangement *arrangementSingle;

@property(nonatomic, readwrite, strong, null_resettable) ProPresenterScreen_CombinedArrangement *arrangementCombined;

@property(nonatomic, readwrite, strong, null_resettable) ProPresenterScreen_EdgeBlendArrangement *arrangementEdgeBlend;

@end

/**
 * Fetches the raw value of a @c ProPresenterScreen's @c screenType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ProPresenterScreen_ScreenType_RawValue(ProPresenterScreen *message);
/**
 * Sets the raw value of an @c ProPresenterScreen's @c screenType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetProPresenterScreen_ScreenType_RawValue(ProPresenterScreen *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'arrangement'.
 **/
void ProPresenterScreen_ClearArrangementOneOfCase(ProPresenterScreen *message);

#pragma mark - ProPresenterScreen_SingleArrangement

typedef GPB_ENUM(ProPresenterScreen_SingleArrangement_FieldNumber) {
  ProPresenterScreen_SingleArrangement_FieldNumber_ScreensArray = 1,
};

GPB_FINAL @interface ProPresenterScreen_SingleArrangement : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Screen*> *screensArray;
/** The number of items in @c screensArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger screensArray_Count;

@end

#pragma mark - ProPresenterScreen_CombinedArrangement

typedef GPB_ENUM(ProPresenterScreen_CombinedArrangement_FieldNumber) {
  ProPresenterScreen_CombinedArrangement_FieldNumber_ScreensArray = 1,
  ProPresenterScreen_CombinedArrangement_FieldNumber_Rows = 2,
  ProPresenterScreen_CombinedArrangement_FieldNumber_Columns = 3,
};

GPB_FINAL @interface ProPresenterScreen_CombinedArrangement : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Screen*> *screensArray;
/** The number of items in @c screensArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger screensArray_Count;

@property(nonatomic, readwrite) uint32_t rows;

@property(nonatomic, readwrite) uint32_t columns;

@end

#pragma mark - ProPresenterScreen_EdgeBlendArrangement

typedef GPB_ENUM(ProPresenterScreen_EdgeBlendArrangement_FieldNumber) {
  ProPresenterScreen_EdgeBlendArrangement_FieldNumber_ScreenCount = 1,
  ProPresenterScreen_EdgeBlendArrangement_FieldNumber_ScreensArray = 2,
  ProPresenterScreen_EdgeBlendArrangement_FieldNumber_EdgeBlendsArray = 3,
};

GPB_FINAL @interface ProPresenterScreen_EdgeBlendArrangement : GPBMessage

@property(nonatomic, readwrite) uint32_t screenCount;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Screen*> *screensArray;
/** The number of items in @c screensArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger screensArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<EdgeBlend*> *edgeBlendsArray;
/** The number of items in @c edgeBlendsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger edgeBlendsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
