// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: planningCenter.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PlanningCenterPlan_PlanItem_Attachment;
@class PlanningCenterPlan_PlanItem_SongItem;
@class PlanningCenterPlan_PlanItem_SongItem_Sequence;
@class Presentation_CCLI;
@class Timestamp;
@class URL;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PlanningCenterPlan_PlanItem_PlanItemType

typedef GPB_ENUM(PlanningCenterPlan_PlanItem_PlanItemType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PlanningCenterPlan_PlanItem_PlanItemType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PlanningCenterPlan_PlanItem_PlanItemType_PlanItemTypeItem = 0,
  PlanningCenterPlan_PlanItem_PlanItemType_PlanItemTypeSong = 1,
  PlanningCenterPlan_PlanItem_PlanItemType_PlanItemTypeMedia = 2,
  PlanningCenterPlan_PlanItem_PlanItemType_PlanItemTypeHeader = 3,
};

GPBEnumDescriptor *PlanningCenterPlan_PlanItem_PlanItemType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PlanningCenterPlan_PlanItem_PlanItemType_IsValidValue(int32_t value);

#pragma mark - PlanningCenterRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface PlanningCenterRoot : GPBRootObject
@end

#pragma mark - PlanningCenterPlan

typedef GPB_ENUM(PlanningCenterPlan_FieldNumber) {
  PlanningCenterPlan_FieldNumber_PlanIdNum = 1,
  PlanningCenterPlan_FieldNumber_ParentIdNum = 2,
  PlanningCenterPlan_FieldNumber_SeriesTitle = 3,
  PlanningCenterPlan_FieldNumber_PlanTitle = 4,
  PlanningCenterPlan_FieldNumber_DateList = 5,
  PlanningCenterPlan_FieldNumber_CreatedDate = 6,
  PlanningCenterPlan_FieldNumber_UpdateDate = 7,
  PlanningCenterPlan_FieldNumber_LastUpdateCheckDate = 8,
  PlanningCenterPlan_FieldNumber_PlanIdStr = 9,
  PlanningCenterPlan_FieldNumber_ParentIdStr = 10,
};

GPB_FINAL @interface PlanningCenterPlan : GPBMessage

@property(nonatomic, readwrite) uint32_t planIdNum;

@property(nonatomic, readwrite) uint32_t parentIdNum;

@property(nonatomic, readwrite, copy, null_resettable) NSString *seriesTitle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *planTitle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *dateList;

@property(nonatomic, readwrite, strong, null_resettable) Timestamp *createdDate;
/** Test to see if @c createdDate has been set. */
@property(nonatomic, readwrite) BOOL hasCreatedDate;

@property(nonatomic, readwrite, strong, null_resettable) Timestamp *updateDate;
/** Test to see if @c updateDate has been set. */
@property(nonatomic, readwrite) BOOL hasUpdateDate;

@property(nonatomic, readwrite, strong, null_resettable) Timestamp *lastUpdateCheckDate;
/** Test to see if @c lastUpdateCheckDate has been set. */
@property(nonatomic, readwrite) BOOL hasLastUpdateCheckDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *planIdStr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *parentIdStr;

@end

#pragma mark - PlanningCenterPlan_PlanItem

typedef GPB_ENUM(PlanningCenterPlan_PlanItem_FieldNumber) {
  PlanningCenterPlan_PlanItem_FieldNumber_ItemType = 1,
  PlanningCenterPlan_PlanItem_FieldNumber_PcoIdNum = 2,
  PlanningCenterPlan_PlanItem_FieldNumber_ServiceIdNum = 3,
  PlanningCenterPlan_PlanItem_FieldNumber_ParentIdNum = 4,
  PlanningCenterPlan_PlanItem_FieldNumber_Name = 5,
  PlanningCenterPlan_PlanItem_FieldNumber_AttachmentsArray = 6,
  PlanningCenterPlan_PlanItem_FieldNumber_UpdateDate = 7,
  PlanningCenterPlan_PlanItem_FieldNumber_LinkedSong = 8,
  PlanningCenterPlan_PlanItem_FieldNumber_PcoIdStr = 9,
  PlanningCenterPlan_PlanItem_FieldNumber_ServiceIdStr = 10,
  PlanningCenterPlan_PlanItem_FieldNumber_ParentIdStr = 11,
};

GPB_FINAL @interface PlanningCenterPlan_PlanItem : GPBMessage

@property(nonatomic, readwrite) PlanningCenterPlan_PlanItem_PlanItemType itemType;

@property(nonatomic, readwrite) uint32_t pcoIdNum;

@property(nonatomic, readwrite) uint32_t serviceIdNum;

@property(nonatomic, readwrite) uint32_t parentIdNum;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PlanningCenterPlan_PlanItem_Attachment*> *attachmentsArray;
/** The number of items in @c attachmentsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger attachmentsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) Timestamp *updateDate;
/** Test to see if @c updateDate has been set. */
@property(nonatomic, readwrite) BOOL hasUpdateDate;

@property(nonatomic, readwrite, strong, null_resettable) PlanningCenterPlan_PlanItem_SongItem *linkedSong;
/** Test to see if @c linkedSong has been set. */
@property(nonatomic, readwrite) BOOL hasLinkedSong;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pcoIdStr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *serviceIdStr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *parentIdStr;

@end

/**
 * Fetches the raw value of a @c PlanningCenterPlan_PlanItem's @c itemType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PlanningCenterPlan_PlanItem_ItemType_RawValue(PlanningCenterPlan_PlanItem *message);
/**
 * Sets the raw value of an @c PlanningCenterPlan_PlanItem's @c itemType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPlanningCenterPlan_PlanItem_ItemType_RawValue(PlanningCenterPlan_PlanItem *message, int32_t value);

#pragma mark - PlanningCenterPlan_PlanItem_Attachment

typedef GPB_ENUM(PlanningCenterPlan_PlanItem_Attachment_FieldNumber) {
  PlanningCenterPlan_PlanItem_Attachment_FieldNumber_Name = 1,
  PlanningCenterPlan_PlanItem_Attachment_FieldNumber_URL = 2,
  PlanningCenterPlan_PlanItem_Attachment_FieldNumber_CreatedDate = 3,
  PlanningCenterPlan_PlanItem_Attachment_FieldNumber_LinkedPath = 4,
  PlanningCenterPlan_PlanItem_Attachment_FieldNumber_PcoIdNum = 5,
  PlanningCenterPlan_PlanItem_Attachment_FieldNumber_NeedsUpdate = 6,
  PlanningCenterPlan_PlanItem_Attachment_FieldNumber_UpdateDate = 7,
  PlanningCenterPlan_PlanItem_Attachment_FieldNumber_PcoIdStr = 8,
};

GPB_FINAL @interface PlanningCenterPlan_PlanItem_Attachment : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) URL *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

@property(nonatomic, readwrite, strong, null_resettable) Timestamp *createdDate;
/** Test to see if @c createdDate has been set. */
@property(nonatomic, readwrite) BOOL hasCreatedDate;

@property(nonatomic, readwrite, strong, null_resettable) URL *linkedPath;
/** Test to see if @c linkedPath has been set. */
@property(nonatomic, readwrite) BOOL hasLinkedPath;

@property(nonatomic, readwrite) uint32_t pcoIdNum;

@property(nonatomic, readwrite) BOOL needsUpdate;

@property(nonatomic, readwrite, strong, null_resettable) Timestamp *updateDate;
/** Test to see if @c updateDate has been set. */
@property(nonatomic, readwrite) BOOL hasUpdateDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pcoIdStr;

@end

#pragma mark - PlanningCenterPlan_PlanItem_SongItem

typedef GPB_ENUM(PlanningCenterPlan_PlanItem_SongItem_FieldNumber) {
  PlanningCenterPlan_PlanItem_SongItem_FieldNumber_PcoIdNum = 1,
  PlanningCenterPlan_PlanItem_SongItem_FieldNumber_ArrangementIdNum = 2,
  PlanningCenterPlan_PlanItem_SongItem_FieldNumber_Ccli = 3,
  PlanningCenterPlan_PlanItem_SongItem_FieldNumber_Sequence = 4,
  PlanningCenterPlan_PlanItem_SongItem_FieldNumber_PcoIdStr = 5,
  PlanningCenterPlan_PlanItem_SongItem_FieldNumber_ArrangementIdStr = 6,
};

GPB_FINAL @interface PlanningCenterPlan_PlanItem_SongItem : GPBMessage

@property(nonatomic, readwrite) uint32_t pcoIdNum;

@property(nonatomic, readwrite) uint32_t arrangementIdNum;

@property(nonatomic, readwrite, strong, null_resettable) Presentation_CCLI *ccli;
/** Test to see if @c ccli has been set. */
@property(nonatomic, readwrite) BOOL hasCcli;

@property(nonatomic, readwrite, strong, null_resettable) PlanningCenterPlan_PlanItem_SongItem_Sequence *sequence;
/** Test to see if @c sequence has been set. */
@property(nonatomic, readwrite) BOOL hasSequence;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pcoIdStr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *arrangementIdStr;

@end

#pragma mark - PlanningCenterPlan_PlanItem_SongItem_Sequence

typedef GPB_ENUM(PlanningCenterPlan_PlanItem_SongItem_Sequence_FieldNumber) {
  PlanningCenterPlan_PlanItem_SongItem_Sequence_FieldNumber_PcoIdNum = 1,
  PlanningCenterPlan_PlanItem_SongItem_Sequence_FieldNumber_Name = 2,
  PlanningCenterPlan_PlanItem_SongItem_Sequence_FieldNumber_GroupNamesArray = 3,
  PlanningCenterPlan_PlanItem_SongItem_Sequence_FieldNumber_PcoIdStr = 4,
};

GPB_FINAL @interface PlanningCenterPlan_PlanItem_SongItem_Sequence : GPBMessage

@property(nonatomic, readwrite) uint32_t pcoIdNum;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *groupNamesArray;
/** The number of items in @c groupNamesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupNamesArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pcoIdStr;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
