// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proAudienceLook.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "ProAudienceLook.pbobjc.h"
#import "BasicTypes.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#pragma mark - Objective C Class declarations
// Forward declarations of Objective C classes that we can use as
// static values in struct initializers.
// We don't use [Foo class] because it is not a static value.
GPBObjCClassDeclaration(ProAudienceLook);
GPBObjCClassDeclaration(ProAudienceLook_ProScreenLook);
GPBObjCClassDeclaration(URL);
GPBObjCClassDeclaration(UUID);

#pragma mark - ProAudienceLookRoot

@implementation ProAudienceLookRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - ProAudienceLookRoot_FileDescriptor

static GPBFileDescriptor *ProAudienceLookRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"rv.data"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - ProAudienceLook

@implementation ProAudienceLook

@dynamic hasUuid, uuid;
@dynamic name;
@dynamic screenLooksArray, screenLooksArray_Count;
@dynamic hasOriginalLookUuid, originalLookUuid;

typedef struct ProAudienceLook__storage_ {
  uint32_t _has_storage_[1];
  UUID *uuid;
  NSString *name;
  NSMutableArray *screenLooksArray;
  UUID *originalLookUuid;
} ProAudienceLook__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "uuid",
        .dataTypeSpecific.clazz = GPBObjCClass(UUID),
        .number = ProAudienceLook_FieldNumber_Uuid,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ProAudienceLook__storage_, uuid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "name",
        .dataTypeSpecific.clazz = Nil,
        .number = ProAudienceLook_FieldNumber_Name,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ProAudienceLook__storage_, name),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "screenLooksArray",
        .dataTypeSpecific.clazz = GPBObjCClass(ProAudienceLook_ProScreenLook),
        .number = ProAudienceLook_FieldNumber_ScreenLooksArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(ProAudienceLook__storage_, screenLooksArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "originalLookUuid",
        .dataTypeSpecific.clazz = GPBObjCClass(UUID),
        .number = ProAudienceLook_FieldNumber_OriginalLookUuid,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ProAudienceLook__storage_, originalLookUuid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ProAudienceLook class]
                                     rootClass:[ProAudienceLookRoot class]
                                          file:ProAudienceLookRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ProAudienceLook__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ProAudienceLook_ProScreenLook

@implementation ProAudienceLook_ProScreenLook

@dynamic hasProScreenUuid, proScreenUuid;
@dynamic propsEnabled;
@dynamic liveVideoEnabled;
@dynamic presentationBackgroundEnabled;
@dynamic hasTemplateDocumentFilePath, templateDocumentFilePath;
@dynamic hasTemplateSlideUuid, templateSlideUuid;
@dynamic presentationForegroundEnabled;
@dynamic hasMaskUuid, maskUuid;
@dynamic announcementsEnabled;
@dynamic propsLayerEnabled;
@dynamic messagesLayerEnabled;

typedef struct ProAudienceLook_ProScreenLook__storage_ {
  uint32_t _has_storage_[1];
  UUID *proScreenUuid;
  URL *templateDocumentFilePath;
  UUID *templateSlideUuid;
  UUID *maskUuid;
} ProAudienceLook_ProScreenLook__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "proScreenUuid",
        .dataTypeSpecific.clazz = GPBObjCClass(UUID),
        .number = ProAudienceLook_ProScreenLook_FieldNumber_ProScreenUuid,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ProAudienceLook_ProScreenLook__storage_, proScreenUuid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "propsEnabled",
        .dataTypeSpecific.clazz = Nil,
        .number = ProAudienceLook_ProScreenLook_FieldNumber_PropsEnabled,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "liveVideoEnabled",
        .dataTypeSpecific.clazz = Nil,
        .number = ProAudienceLook_ProScreenLook_FieldNumber_LiveVideoEnabled,
        .hasIndex = 3,
        .offset = 4,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "presentationBackgroundEnabled",
        .dataTypeSpecific.clazz = Nil,
        .number = ProAudienceLook_ProScreenLook_FieldNumber_PresentationBackgroundEnabled,
        .hasIndex = 5,
        .offset = 6,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "templateDocumentFilePath",
        .dataTypeSpecific.clazz = GPBObjCClass(URL),
        .number = ProAudienceLook_ProScreenLook_FieldNumber_TemplateDocumentFilePath,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(ProAudienceLook_ProScreenLook__storage_, templateDocumentFilePath),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "templateSlideUuid",
        .dataTypeSpecific.clazz = GPBObjCClass(UUID),
        .number = ProAudienceLook_ProScreenLook_FieldNumber_TemplateSlideUuid,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(ProAudienceLook_ProScreenLook__storage_, templateSlideUuid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "presentationForegroundEnabled",
        .dataTypeSpecific.clazz = Nil,
        .number = ProAudienceLook_ProScreenLook_FieldNumber_PresentationForegroundEnabled,
        .hasIndex = 9,
        .offset = 10,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "maskUuid",
        .dataTypeSpecific.clazz = GPBObjCClass(UUID),
        .number = ProAudienceLook_ProScreenLook_FieldNumber_MaskUuid,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(ProAudienceLook_ProScreenLook__storage_, maskUuid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "announcementsEnabled",
        .dataTypeSpecific.clazz = Nil,
        .number = ProAudienceLook_ProScreenLook_FieldNumber_AnnouncementsEnabled,
        .hasIndex = 12,
        .offset = 13,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "propsLayerEnabled",
        .dataTypeSpecific.clazz = Nil,
        .number = ProAudienceLook_ProScreenLook_FieldNumber_PropsLayerEnabled,
        .hasIndex = 14,
        .offset = 15,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "messagesLayerEnabled",
        .dataTypeSpecific.clazz = Nil,
        .number = ProAudienceLook_ProScreenLook_FieldNumber_MessagesLayerEnabled,
        .hasIndex = 16,
        .offset = 17,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ProAudienceLook_ProScreenLook class]
                                     rootClass:[ProAudienceLookRoot class]
                                          file:ProAudienceLookRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ProAudienceLook_ProScreenLook__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    [localDescriptor setupContainingMessageClass:GPBObjCClass(ProAudienceLook)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
