// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propresenter.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Action_Label;
@class ApplicationInfo;
@class Playlist;
@class Playlist_Tag;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PlaylistDocument_Type

typedef GPB_ENUM(PlaylistDocument_Type) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PlaylistDocument_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PlaylistDocument_Type_TypeUnknown = 0,
  PlaylistDocument_Type_TypePresentation = 1,
  PlaylistDocument_Type_TypeMedia = 2,
  PlaylistDocument_Type_TypeAudio = 3,
};

GPBEnumDescriptor *PlaylistDocument_Type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PlaylistDocument_Type_IsValidValue(int32_t value);

#pragma mark - PropresenterRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface PropresenterRoot : GPBRootObject
@end

#pragma mark - PlaylistDocument

typedef GPB_ENUM(PlaylistDocument_FieldNumber) {
  PlaylistDocument_FieldNumber_ApplicationInfo = 1,
  PlaylistDocument_FieldNumber_Type = 2,
  PlaylistDocument_FieldNumber_RootNode = 3,
  PlaylistDocument_FieldNumber_TagsArray = 4,
  PlaylistDocument_FieldNumber_LiveVideoPlaylist = 5,
  PlaylistDocument_FieldNumber_DownloadsPlaylist = 6,
};

GPB_FINAL @interface PlaylistDocument : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ApplicationInfo *applicationInfo;
/** Test to see if @c applicationInfo has been set. */
@property(nonatomic, readwrite) BOOL hasApplicationInfo;

@property(nonatomic, readwrite) PlaylistDocument_Type type;

@property(nonatomic, readwrite, strong, null_resettable) Playlist *rootNode;
/** Test to see if @c rootNode has been set. */
@property(nonatomic, readwrite) BOOL hasRootNode;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Playlist_Tag*> *tagsArray;
/** The number of items in @c tagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) Playlist *liveVideoPlaylist;
/** Test to see if @c liveVideoPlaylist has been set. */
@property(nonatomic, readwrite) BOOL hasLiveVideoPlaylist;

@property(nonatomic, readwrite, strong, null_resettable) Playlist *downloadsPlaylist;
/** Test to see if @c downloadsPlaylist has been set. */
@property(nonatomic, readwrite) BOOL hasDownloadsPlaylist;

@end

/**
 * Fetches the raw value of a @c PlaylistDocument's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PlaylistDocument_Type_RawValue(PlaylistDocument *message);
/**
 * Sets the raw value of an @c PlaylistDocument's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPlaylistDocument_Type_RawValue(PlaylistDocument *message, int32_t value);

#pragma mark - SettingsDocument

typedef GPB_ENUM(SettingsDocument_FieldNumber) {
  SettingsDocument_FieldNumber_LabelsArray = 2,
};

GPB_FINAL @interface SettingsDocument : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Action_Label*> *labelsArray;
/** The number of items in @c labelsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger labelsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
